//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int ID { get; set; }
        public string STUDENT_NAME { get; set; }
        public string STUDENT_LNAME { get; set; }
        public Nullable<System.DateTime> STUDENT_BIRTH_DATE { get; set; }
    }
}
